name: Info do Push

on:
  push:
    branches: [main]

jobs:
  info:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do c칩digo
        uses: actions/checkout@v4

      - name: Mostrar data e hora do push (Hor치rio do Brasil)
        run: |
          echo "Data e hora do push (Brasil):"
          TZ='America/Sao_Paulo' date "+%d/%m/%Y %H:%M:%S"

      - name: Mostrar usu치rio do push
        run: |
          echo "Usu치rio que fez o push: ${{ github.actor }}"
